# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Insira o ticker do ativo', max_length=10)),
            ],
        ),
    ]
