# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='ticker',
            field=models.CharField(help_text='Insira o ticker do ativo', max_length=15),
        ),
    ]
