# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180405_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickerA', models.CharField(help_text='Insira o ticker do ativo', max_length=10)),
                ('tickerB', models.CharField(help_text='Insira o ticker do ativo', max_length=10)),
                ('tickerC', models.CharField(help_text='Insira o ticker do ativo', max_length=10)),
                ('tickerD', models.CharField(help_text='Insira o ticker do ativo', max_length=10)),
                ('tickerE', models.CharField(help_text='Insira o ticker do ativo', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='input',
            name='ticker',
            field=models.CharField(help_text='Insira o ticker do ativo', max_length=10),
        ),
    ]
